ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.vinish.plugins.RoutingKt.configureRouting
      - com.vinish.plugins.StatusPagesKt.configureStatusPages
      - com.vinish.plugins.SerializationKt.configureSerialization
